Repository atlp-rwanda/trojans-ec-bn, pull requests merged in 2023-03, with the labels that each got.

#107 #184347116 - chat bot code
  .DS_Store
  package-lock.json
  package.json
  src/controllers/chatController.js
  src/database/migrations/20230217122520-create-message.js
  src/database/models/message.js
  src/database/seeders/20230302074002-message.js
  src/documentation/index.js
  src/index.js
  src/public/index.html
  src/public/script.js
  src/routes/api/chat.route.js
  src/routes/index.js
  src/services/chatServices.js
  src/utils/bcrypt.js
  src/utils/socketio.js
  tests/chatbot.test.js
Labels: backend, devops

#110 #184347082 - Setting up docker
  .dockerignore
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/utils/bcrypt.js
  src/utils/socketio.js
Labels: documentation, backend, devops, chore

#115 184557824 Ft change Sale status
  package-lock.json
  src/controllers/paymentController.js
  src/controllers/productController.js
  src/controllers/productWishesController.js
  src/controllers/saleController.js
  src/database/migrations/20230227091718-create-order.js
  src/database/migrations/20230305204840-create-sales.js
  src/database/models/order.js
  src/database/models/ratings.js
  src/database/models/user.js
  src/database/seeders/20230308162934-Order.js
  src/database/seeders/20230308162947-Sales.js
  src/documentation/index.js
  src/middlewares/changeSale.js
  src/middlewares/checkOwner.js
  src/middlewares/checkSaleExist.js
  src/middlewares/checkSaleOwner.js
  src/middlewares/checkUserCartExist.js
  src/middlewares/isBought.js
  src/routes/api/sale.route.js
  src/routes/index.js
  src/services/paymentService.js
  src/services/productWishesService.js
  src/services/saleService.js
  src/validations/sales.validation.js
  tests/sale.test.js
Labels: documentation, devops, chore

#119 ## - bug fix on different responses & upload image
  package-lock.json
  package.json
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/checkOwner.js
  src/middlewares/checkProductExist.js
  src/middlewares/uploadCloud.js
  src/routes/api/product.route.js
  src/routes/api/user.route.js
  src/routes/index.js
  src/services/productService.js
  src/validations/pass.reset.validation.js
  src/validations/product.validation.js
  tests/sample.test.js
Labels: backend, devops, Read for Review, Bug FIxing

#122 #184347111-Mark Notifications
  package-lock.json
  src/controllers/notificationController.js
  src/controllers/productController.js
  src/documentation/index.js
  src/middlewares/checkNotification.js
  src/middlewares/checkUserExist.js
  src/middlewares/checkUserStatus.js
  src/routes/api/notification.route.js
  src/routes/api/user.route.js
  src/services/notificationServices.js
  tests/notifications.test.js
  tests/sample.test.js
Labels: backend, devops

#120 ## - Bug fix on login and expired product
  src/app.js
  src/controllers/productController.js
  src/controllers/saleController.js
  src/database/models/sales.js
  src/database/seeders/20230216052317-product.js
  src/database/seeders/20230308162947-Sales.js
  src/documentation/index.js
  src/middlewares/changeSale.js
  src/middlewares/checkProductExpired.js
  src/middlewares/checkSaleExist.js
  src/middlewares/isBought.js
  src/middlewares/isUserAuth.js
  src/routes/api/product.route.js
  src/routes/api/sale.route.js
  src/routes/api/user.route.js
  src/services/productService.js
  src/services/saleService.js
  src/utils/local.passport.js
  src/utils/passport.js
  tests/product.test.js
  tests/sale.test.js
  tests/sample.test.js
Labels: backend, devops, Bug FIxing
