Repository atlp-rwanda/trojans-ec-bn, pull requests merged in 2023-02, with the labels that each got.

#56 Added the registration route
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230131184523-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/middlewares/validations/signupValidation.js
  src/routes/api/user.route.js
  src/routes/index.js
  tests/sample.test.js
Labels: backend, devops

#57 #184347075 ESLint is the required linter for the project. It'll help check for style violations and flag them.
  .circleci/config.yml
  .eslintrc.js
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
  src/app.js
  src/config/index.js
  src/controllers/index.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230131184523-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230130162314-demo-user.js
  src/documentation/index.js
  src/middlewares/index.js
  src/middlewares/validations/signupValidation.js
  src/routes/api/home.route.js
  src/routes/api/user.route.js
  src/routes/index.js
  src/utils/index.js
  tests/sample.test.js
Labels: backend, chore

#59 #184347076 Integrate HoundCI with badge attached to readme
  .hound.yml
  README.md
Labels: backend, devops, chore

#58 Ch setup swagger 184347080
  package-lock.json
  package.json
  src/app.js
  src/documentation/home.js
  src/documentation/index.js
  tests/sample.test.js
Labels: backend, chore

#64 #184347075 Refactor Configure ESLint
  .eslintrc.js
  .eslintrc.json
  .hound.yml
  src/app.js
  src/controllers/userController.js
  src/database/migrations/20230131184523-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230130162314-demo-user.js
  tests/sample.test.js
Labels: duplicate, backend, chore

#65 #184347083 - added swagger documentation for the signup
  src/documentation/index.js
Labels: backend, devops

#60 184347087 Ft user login
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/migrations/20230131072323-create-user.js
  src/documentation/index.js
  src/routes/api/user.route.js
  src/utils/passport.config.js
  src/validation/user.vald.js
  tests/sample.test.js
Labels: documentation, backend, devops

#73 #0 - refactored codes to use services and utils
  src/config/.gitkeep
  src/config/index.js
  src/controllers/index.js
  src/controllers/userController.js
  src/middlewares/index.js
  src/middlewares/verifyUser.js
  src/routes/api/user.route.js
  src/services/userService.js
  src/utils/bcrypt.js
  src/utils/generateToken.js
  src/utils/index.js
  src/utils/passport.config.js
  src/utils/passport.js
  src/validation/user.vald.js
  src/validations/login.validation.js
  src/validations/signup.validation.js
Labels: bug, backend

#81 ##184347089 - Update and reset password
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/documentation/index.js
  src/middlewares/checkPass.js
  src/middlewares/extractToken.js
  src/middlewares/resetData.js
  src/middlewares/verifyUser.js
  src/routes/api/test.route.js
  src/routes/api/user.route.js
  src/routes/index.js
  src/services/userService.js
  src/utils/emailHtml.js
  src/utils/generateToken.js
  src/utils/sendmail.js
  src/validations/pass.reset.validation.js
  src/validations/pass.update.validation.js
  tests/sample.test.js
Labels: documentation, backend, devops

#76 #184347090-two-factor-authentication-for-sellers
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/migrations/20230209080557-create-user.js
  src/documentation/index.js
  src/emailTemplate/2FAToken.ejs
  src/middlewares/findUser.js
  src/routes/api/user.route.js
  src/services/userService.js
  src/utils/email.js
  src/utils/findUser.js
  src/utils/generateRandom.js
  src/utils/generateToken.js
  src/utils/send2FA.js
  src/utils/userFind.js
  tests/sample.test.js
Labels: documentation, backend, devops

#83 184347088 Ft google login
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/migrations/20230207053009-create-user.js
  src/database/seeders/20230130162314-demo-user.js
  src/database/seeders/20230209182413-User.js
  src/documentation/index.js
  src/middlewares/checkPass.js
  src/middlewares/selectRole.js
  src/routes/api/user.route.js
  src/services/userService.js
  src/utils/bcrypt.js
  src/utils/find.js
  src/utils/googleAuth.js
  src/utils/passport.config.js
  src/utils/passport.js
  src/validations/role.validation.js
  tests/mock/user.mock.data.js
  tests/sample.test.js
Labels: backend, devops

#86 #184347086 Logout Functionality
  .gitignore
  package.json
  src/controllers/userController.js
  src/database/migrations/20230210121434-create-blacklist.js
  src/database/models/blacklist.js
  src/documentation/index.js
  src/middlewares/extractToken.js
  src/routes/api/user.route.js
  src/services/userService.js
  tests/sample.test.js
Labels: documentation, backend

#77 #184347091 Profile Page Settings
  package-lock.json
  package.json
  src/app.js
  src/controllers/notFound.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230207053009-create-user.js
  src/database/migrations/20230209080557-create-user.js
  src/database/migrations/20230210121434-create-blacklist.js
  src/database/models/user.js
  src/database/seeders/20230209182413-User.js
  src/documentation/index.js
  src/middlewares/extractToken.js
  src/routes/api/user.route.js
  src/services/userService.js
  src/utils/clodinary.config.js
  src/utils/multer.js
  src/validations/profile.update.validation.js
  src/validations/signup.validation.js
  tests/mock/user.mock.data.js
  tests/sample.test.js
Labels: documentation, backend

#90 #184347095 - create/add item or product
  package-lock.json
  package.json
  src/config/.gitkeep
  src/config/cloudinary.js
  src/config/multer.js
  src/controllers/notFound.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230211060158-create-category.js
  src/database/migrations/20230214132539-create-product.js
  src/database/models/category.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230209182413-User.js
  src/database/seeders/20230214145541-product.js
  src/documentation/index.js
  src/middlewares/alreadyExists.js
  src/middlewares/checkAdmin.js
  src/middlewares/checkSeller.js
  src/middlewares/checkUserVerification.js
  src/middlewares/resetData.js
  src/middlewares/verifyProduct.js
  src/middlewares/verifyToken.js
  src/routes/api/category.route.js
  src/routes/api/product.route.js
  src/routes/api/user.route.js
  src/routes/index.js
  src/services/productService.js
  src/services/userService.js
  src/utils/bcrypt.js
  src/utils/googleAuth.js
  src/utils/multer.js
  src/utils/passport.config.js
  src/validations/product.validation.js
  src/validations/role.validation.js
  tests/mock/product.mock.data.js
  tests/sample.test.js
Labels: documentation, backend, devops

#92 #184347099 - viewing products both single view and all view
  package.json
  src/controllers/notFound.js
  src/controllers/productController.js
  src/database/seeders/20230209182413-User.js
  src/database/seeders/20230214145541-category.js
  src/database/seeders/20230216052317-product.js
  src/documentation/index.js
  src/middlewares/extractToken.js
  src/routes/api/product.route.js
  src/services/productService.js
  tests/sample.test.js
Labels: documentation, backend, devops

#96 #1 - Bg google login and delete category
  src/controllers/productController.js
  src/controllers/userController.js
  src/documentation/index.js
  src/emailTemplate/googlePassword.ejs
  src/middlewares/verifyProduct.js
  src/routes/api/category.route.js
  src/services/productService.js
  src/services/userService.js
  src/utils/email.js
  tests/mock/user.mock.data.js
  tests/sample.test.js
Labels: backend, devops, Bug FIxing

#99 #184347107-search-products
  .gitignore
  .ignore
  package.json
  src/controllers/productController.js
  src/controllers/productWishesController.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230216073036-create-product-wishes.js
  src/database/models/category.js
  src/database/models/product.js
  src/database/models/productwishes.js
  src/database/models/user.js
  src/database/seeders/20230209182413-User.js
  src/database/seeders/20230214145541-category.js
  src/database/seeders/20230216052317-product.js
  src/database/seeders/20230216134243-ProductWishes.js
  src/documentation/index.js
  src/middlewares/checkProductExist.js
  src/middlewares/checkUserExist.js
  src/routes/api/product.route.js
  src/routes/api/product_wishes.route.js
  src/routes/api/user.route.js
  src/services/productService.js
  src/services/productWishesService.js
  src/utils/searchUtil.js
  src/validations/query.validation.js
  tests/sample.test.js
Labels: documentation, enhancement, backend, devops

#100 A Seller's ability to mark product/item availability,delete and update
  .DS_Store
  .gitignore
  package-lock.json
  src/.DS_Store
  src/controllers/productController.js
  src/database/.DS_Store
  src/database/seeders/20230216052317-product.js
  src/documentation/index.js
  src/middlewares/checkOwner.js
  src/routes/api/product.route.js
  src/services/productService.js
  src/validations/product.validation.js
  tests/mock/product.mock.data.js
  tests/sample.test.js
Labels: backend, devops

#103 #184347107-fixed-bug-and-added-the-missing-features
  src/controllers/productController.js
  src/services/productService.js
  src/utils/searchUtil.js
Labels: Bug FIxing

#101 #184347113 Prompted a user to change password.
  .eslintrc.json
  .hound.yml
  package-lock.json
  package.json
  src/app.js
  src/config/cloudinary.js
  src/config/multer.js
  src/controllers/productController.js
  src/controllers/productWishesController.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20230207053009-create-user.js
  src/database/migrations/20230209080557-create-user.js
  src/database/migrations/20230210121434-create-blacklist.js
  src/database/migrations/20230211060158-create-category.js
  src/database/migrations/20230214132539-create-product.js
  src/database/migrations/20230216073036-create-product-wishes.js
  src/database/models/blacklist.js
  src/database/models/product.js
  src/database/models/productwishes.js
  src/database/models/user.js
  src/database/seeders/20230209182413-User.js
  src/database/seeders/20230214145541-category.js
  src/database/seeders/20230216052317-product.js
  src/database/seeders/20230216134243-ProductWishes.js
  src/emailTemplate/expiredPassword.ejs
  src/emailTemplate/passwordUpdated.ejs
  src/events/eventEmitter/user.js
  src/events/eventHandler/user.js
  src/middlewares/isPasswordExpired.js
  src/middlewares/resetData.js
  src/middlewares/verifyProduct.js
  src/routes/api/category.route.js
  src/routes/api/product.route.js
  src/routes/api/product_wishes.route.js
  src/routes/api/user.route.js
  src/routes/index.js
  src/services/productService.js
  src/services/productWishesService.js
  src/services/userService.js
  src/utils/email.js
  src/utils/isPasswordExpired.js
  src/utils/searchUtil.js
  src/validations/profile.update.validation.js
  tests/sample.test.js
  tests/user.events.test.js
Labels: enhancement, backend, chore, Read for Review, automatic action, authentication

#104 #184347103 crud operation of cart
  .eslintrc.json
  src/controllers/CartController.js
  src/controllers/userController.js
  src/database/migrations/20230220100400-create-cart.js
  src/database/models/cart.js
  src/database/models/user.js
  src/documentation/index.js
  src/routes/api/cart.route.js
  src/routes/index.js
  src/services/CartServices.js
  tests/sample.test.js
Labels: backend

#106 debugging for product expired
  src/database/seeders/20230209182413-User.js
  src/routes/api/cart.route.js
  src/services/CartServices.js
  src/services/productService.js
Labels: Bug FIxing
